(ns tvm-clj.compute.compile-fn
  (:require [tvm-clj.core :as c]
            [tvm-clj.api :as api]
            [tvm-clj.base :as b]
            [tvm-clj.compute.registry :as tvm-reg]
            [tvm-clj.compiler.graph :as g]
            [tvm-clj.compiler.ast :as ast]
            [tech.compute.driver :as drv]
            [tech.compute.tensor.dimensions :refer [when-not-error] :as ct-dims]
            [tech.datatype.base :as dtype]
            [clojure.core.matrix.protocols :as mp]
            [tech.compute.tensor :as ct]
            [clojure.set :as c-set]
            [tvm-clj.compute.tensor-math :as tm]
            [clojure.string :as c-str]
            [tech.compute.tensor.utils :as tens-utils]
            [clojure.string :as s]))
