#!/bin/bash


pushd test/data
for FILE in train-images-idx3-ubyte.gz train-labels-idx1-ubyte.gz t10k-images-idx3-ubyte.gz t10k-labels-idx1-ubyte.gz
do
    wget http://yann.lecun.com/exdb/mnist/$FILE
    gunzip $FILE
done
popd
